README.md
src/index.js
test/index.spec.js

adds feature needed for https://github.com/libp2p/js-libp2p-ping/pull/38
> PS: I got very confused by the amount of times that the words `crypto` and `webcrypto` appear interleave throughout the code (ie. crypto = require(webcrypto) & crypto.webcrypto 💥).

feat: add randomBytes function

---

src/index.js

This allows other modules to reuse the protobuf definition
cc @yusefnapora

feat: expose protobuf

---

src/crypto/webcrypto-browser.js

Full WebWorker compatibility ipfs/js-ipfs#725

feat: change window to self for webworker support

---

.travis.yml
benchmarks/ephemeral-keys.js
benchmarks/key-stretcher.js
benchmarks/rsa.js
circle.yml
package.json
src/hmac/index-browser.js
src/keys/ecdh-browser.js
src/keys/ed25519-class.js
src/keys/ed25519.js
src/keys/key-stretcher.js
src/keys/rsa-browser.js
src/util.js
test/aes/aes.spec.js
test/fixtures/go-elliptic-key.js
test/fixtures/go-key-ed25519.js
test/fixtures/go-key-rsa.js
test/fixtures/go-stretch-key.js
test/fixtures/secp256k1.js
test/hmac/hmac.spec.js
test/keys/ed25519.spec.js
test/keys/rsa.spec.js

Blocked by https://github.com/facebook/jest/issues/4422

feat: upgrade to aegir@12

---

package.json
src/keys/ed25519-class.js
src/keys/index.js
src/keys/rsa-class.js

Ref https://github.com/ipfs/js-ipfs/issues/991

feat: switch protocol-buffers to protons

---

package.json
src/keys/rsa.js
test/keys/rsa-crypto-libs.js
test/node.js

The difference between ursa and ursa-optional is that ursa-optional does not cause any problems if it fails to compile

feat: use ursa-optional for lightning fast key generation

---

README.md

fix: fix links in README

---

.travis.yml
package.json

This brings compatiability with node@12 for the native dependency

fix(deps): update to ursa-optiona@0.10

---

package.json
src/aes/cipher-mode.js
src/aes/index-browser.js
src/aes/index.js
src/keys/ecdh-browser.js
src/keys/ecdh.js
src/keys/ed25519-class.js
src/keys/index.js
src/keys/key-stretcher.js
src/keys/rsa-class.js
src/keys/rsa.js
src/keys/validate-curve-type.js
src/pbkdf2.js
src/random-bytes.js
test/aes/aes.spec.js
test/crypto.spec.js
test/helpers/test-garbage-error-handling.js
test/keys/ed25519.spec.js
test/keys/ephemeral-keys.spec.js
test/keys/key-stretcher.spec.js
test/keys/rsa.spec.js
test/random-bytes.spec.js
test/util/index.js

Fixes https://github.com/libp2p/js-libp2p-crypto/issues/152

chore: add error codes

---

src/keys/exporter.js
src/keys/importer.js

Not sure how this fell through the cracks.

chore: remove multibase reference

---

package.json

closes #197 
while i where at it, i think sinon is not being used either?

remove unused is-typedarray

---

benchmarks/ed25519/compat.js
benchmarks/ed25519/index.js
benchmarks/ed25519/package.json
package.json

Pulls the benchmark suite out of #211 so it can be merged independently.

chore: add Ed25519 benchmark suite

---

.github/workflows/main.yml
package.json

chore: add auto-publish

---

.github/workflows/main.yml

No script declared, will not run

chore: uncomment renderer build

---

benchmarks/ed25519/package.json

chore: update benchmark deps

---

package.json

Updates node-forge to the latest version

chore: update node-forge

---

package.json

Revert #239 now that the issue has been fixed

fix: upgrade ed25519

---

package.json
src/keys/index.ts

Adds return types to exported key functions

fix: add return types to key methods

---

README.md
package.json
src/keys/index.ts

BREAKING CHANGE: uses new single-issue libp2p interface modules

feat!: update to latest libp2p interfaces

---

.gitignore
package.json
src/keys/index.ts
src/keys/keys.proto
src/keys/keys.ts
test/keys/secp256k1.spec.ts

Regenerate files to use new protons runtime

deps: update protons-runtime and protons
