src/crypto/util.js, test/util.spec.js
`util.toBase64` would throw an error as `bn.toBuffer` doesn't work with browserify. `bn.toArrayLike` is used instead. 
`bn.toBuffer` is a simple wrapper for `bn.toArrayLike` anyway so there are no downsides here between node/browser.
https://github.com/indutny/bn.js/blob/master/lib/bn.js#L516
Fixes: #41
=> Fix for browserify 

package.json
This works around the issue that browserify throws on missing modules.
Ref #70
=> fix: use browserify-optional

src/crypto/ed25519.js, src/index.js, src/keys/ed25519.js, test/ed25519.spec.js
This will produce the same keypair for the same seed (or first 32 bytes of reader) as given to GenerateKeyPairWithReader in go-libp2p. Solves #84 for ed25519.
=> Implement generateKeyPairFromSeed for ed25519

src/crypto/ecdh-browser.js, src/crypto/util.js, test/util.spec.js
JWK format, at least for elliptical key import, requires x and y values (base64 encoded) to be an expected byte length, so the buffer that comes out of the bn.js toArrayLike function must be left padded. Currently if the first byte of 32 is 0, a 31 byte buffer is returned from toArrayLike, and the resulting base64 reflects this. If 32 is passed to the toBase64() function as 'len', then the first byte is now set as 0.
This fixes #97. There may be similar issues elsewhere, in which case they can also pass a length value to toBase64(). In the meantime, this fixes unmarshalPublicKey() in ecdh-browser.js
=> Allow base64 to be left 0 padded, and do so in ecdh key unmarshalling

package.json, src/hmac/index-browser.js, src/keys/ecdh-browser.js, src/keys/rsa-browser.js, src/nodeify.js
We don't need it in our usage, as the promises we are transforming are always async.
Ref https://github.com/ipfs/js-ipfs/issues/128
=> Skip nextTick in nodeify

src/keys/ed25519.js, src/keys/index.js, src/keys/rsa.js, test/crypto.spec.js, test/helpers/test-garbage-error-handling.js, test/keys/ed25519.spec.js, test/keys/rsa.spec.js, test/keys/secp256k1.spec.js, test/testCb.js
=> Catch error when unmarshaling instead of crashing

README.md, package.json, src/index.js, src/keys/ed25519-class.js, src/keys/index.js, src/keys/rsa-browser.js, src/keys/rsa-class.js, src/pbkdf2.js, test/crypto.spec.js, test/keys/ed25519.spec.js, test/keys/rsa.spec.js
This uses the [jsrsasign](https://www.npmjs.com/package/jsrsasign) package to create password protected private keys.
Currently, it only works with RSA key types.
See issue https://github.com/libp2p/js-libp2p-crypto/issues/114
PR https://github.com/libp2p/js-libp2p-keychain/pull/18 is dependent upon this PR
=> Key exchange with jsrsasign

package.json, src/keys/index.js, src/keys/rsa-class.js, src/pbkdf2.js, test/crypto.spec.js, test/keys/rsa.spec.js
`jsrsasign` is 2 orders of magnitude slower that `node-forge`; see the [benchmarks](https://github.com/richardschneider/crypto-benchmarks).
[node-forge](https://unpkg.com/node-forge/dist/) is a little bigger than [jsrsasign](https://unpkg.com/jsrsasign/lib/) (273 kB vs 259 kB).
`libp2p-crypto` relies upon `keypair` for RSA.  It is 128 kB.  `keypair` has copied `node-forge` code from 5 years ago and has added JWK support.  If we make a JWK PR to forge, then we can remove the the `keypair` dependency.
=> Improve speed

package.json
Hey @dignifiedquire It seems like this repo also needs to update the dependency as https://github.com/libp2p/js-libp2p-keychain depends on this one
=> chore: updates libp2p-crypto-secp256k1

src/keys/rsa-class.js, test/keys/rsa.spec.js
Fixes https://github.com/libp2p/js-libp2p-crypto/issues/153
Note: This probably isn't going to require any upstream code changes, because there is only one allowed export format and it's the default
=> fix: put optional args last for key export

package.json, test/keys/secp256k1.spec.js
Upgrade libp2p-crypto-secp256k1 dependency and ensure that Secp256k1 supported is tested properly.
=> Upgrade libp2p-crypto-secp256k1 + fix Secp256k1 tests

README.md, src/hmac/index-browser.js, src/keys/ecdh-browser.js, src/keys/rsa-browser.js, src/webcrypto.js, test/browser.js
This PR simply detects missing web crypto and throws an error with an appropriate message.
This is a stepping stone that will help users understand the problem until we have time to do a refactor of this module and of all the modules that use it to enable optionally passing your own crypto implementation.
refs https://github.com/libp2p/js-libp2p-crypto/pull/149
refs https://github.com/libp2p/js-libp2p-crypto/pull/150
refs https://github.com/libp2p/js-libp2p-crypto/issues/105
refs https://github.com/ipfs/js-ipfs/issues/2153
refs https://github.com/ipfs/js-ipfs/issues/2017
=> fix: better error for missing web crypto

package.json, src/keys/index.js, src/keys/key-stretcher.js, src/util.js, test/helpers/test-garbage-error-handling.js, test/util.spec.js
Upgrades `node-forge` dependency to the same one used by `libp2p-keychain` in order to downgrade `libp2p-keychain`'s `peer-id` dependency to the same version as the `libp2p` in order to upgrade `ipfs` to use the latest `libp2p` and still be able to dial other nodes on the network.
Phew.
This is necessary because otherwise `node-forge` complains that `sha512` is an unknown hash algorithm.
N.b. this PR is against the branch `v0.16.x` and not master, which is `v0.17.0` so needs to be released as `0.16.2`.
Also upgrades `aegir` to `v20` because for whatever reason the tests weren't running on browsers with `v18` any more.  It upgrades `standard` so there's some refactoring noise in this PR.
=> V0.16.x upgrade node forge

README.md, package.json
I am proposing to take over Lead Maintainer of libp2p-crypto.
If approved, I will need npm publish permissions.
=> chore: change lead maintainer

.aegir.js, .travis.yml, package.json, src/keys/index.js, src/keys/jwk2pem.js, src/keys/key-stretcher.js, src/keys/rsa-browser.js, src/keys/rsa-class.js, src/keys/rsa.js, src/util.js, test/helpers/test-garbage-error-handling.js, test/keys/ephemeral-keys.spec.js, test/keys/rsa.spec.js, test/util.spec.js
Fixes https://github.com/libp2p/js-peer-id/issues/80
=> feat: Add (rsa)pubKey.encrypt and (rsa)privKey.decrypt

src/keys/jwk2pem.js
These two unused functions required us to import the whole of the node-forge PKI implementation when we only use some RSA stuffs.
I thought this was going to lead to a big saving but then I realised that `libp2p-keychain` requires `pkcs7` from `node-forge` which brings in a bunch of other modules...
It saves 34KB, but that only translates to 2KB when minified and gzipped. Still it's something, and I've done the research work now so might as well submit it 🤷‍♂️
---
Before:
After:
=> perf: remove jwk2privPem and jwk2pubPem

package.json, src/keys/ecdh-browser.js, src/keys/jwk2pem.js, src/keys/rsa-utils.js, src/util.js, test/util.spec.js
We are already using `asn1` from `node-forge` in the code base. This PR removes the `asn1.js` dependency and uses the code we already imported from `node-forge` instead.
It should remove ~20 KB (gzipped) from the bundle.
---
https://tools.ietf.org/html/rfc7518
=> perf: remove asn1.js and use node-forge

package.json
I'm seeing two copies of `node-forge` in the js-IPFS bundle, my guess is because libp2p uses a `^` character for version selection and this module uses `~`.
The change here brings the version number into line with libp2p.
=> chore: update node forge version

README.md, package.json, src/ciphers/aes-gcm.browser.js, src/ciphers/aes-gcm.js, src/index.d.ts, src/keys/ed25519-class.js, src/keys/exporter.js, src/keys/importer.js, src/keys/index.js, src/keys/rsa-class.js, src/keys/rsa-utils.js, src/keys/secp256k1-class.js, test/browser.js, test/keys/ed25519.spec.js, test/keys/rsa.spec.js, test/keys/secp256k1.spec.js
This PR adds support for exporting/importing all keys in the `libp2p-key` format discussed in https://github.com/libp2p/js-libp2p-crypto/issues/145#issuecomment-661251436. This is designed to be a non breaking change. A future breaking change should update the default export of rsa to also be `libp2p-key` and provide an example for how to perform the migration of previously used keys.
Exported keys are encrypted via the AES-GCM algorithm using password derived PBKDF2 keys. They are exported as base64 encoded strings. I originally considered prefixing the exported bytes with a multibase prefix/multicodec prefix to make it easier to determine key type, but this would violate other formats like PEM, so we wouldn't get any meaningful reusability out of this.
This leverages Node.js and …
=> feat: add exporting/importing of non rsa keys in libp2p-key format

src/keys/ed25519-class.js, test/keys/ed25519.spec.js
BREAKING CHANGE: The private ed25519 key will no longer include the redundant public key
This is the breaking change portion of https://github.com/libp2p/js-libp2p-crypto/pull/178, which completes the coversion.
=> fix: remove rendundant public key

src/index.d.ts
tested locally, I couldn't find any use of the node types here.
With this node type, there is a required peer dependency of `@types/node`
=> chore: remove unused type

package.json, src/keys/ed25519-class.js, test/keys/ed25519.spec.js
This commit pushes further fixes to the generation of Ed25519 peer IDs,
building upon the discussion in ipfs/js-ipfs#3591 and the subsequent
pull request libp2p/js-libp2p-crypto#185.
The purpose of this new pull request is to harmonize the encoding of
PeerIDs for Ed25519 keys such that the same new format is used
everywhere: peer IDs when assigned upon key generation, peer IDs when
shown via key listing, as well as the peer IDs displayed as IPNS names
when the key is used as the basis for an IPNS record.
Concretely, this changes the peer ID representation of Ed25519 keys from
the `Qm...` format to the newer `1...` format.
The accompanying test has been modified accordingly.
=> Fix Ed25519 PeerID generation

.aegir.js, .travis.yml, package.json, src/ciphers/aes-gcm.browser.js, src/ciphers/aes-gcm.js, src/keys/ed25519-class.js, src/keys/exporter.js, src/keys/importer.js, src/keys/index.js, src/keys/keys.js, src/keys/keys.proto, src/keys/rsa-class.js, src/keys/secp256k1-class.js, src/pbkdf2.js, test/crypto.spec.js, test/keys/ed25519.spec.js
Updates dependencies to the latest versions to dedupe the dependency tree.
This also removes protons in favour of protobufjs for smaller bundles
=> chore: update deps

package.json, src/keys/ed25519-class.js, src/keys/rsa-class.js, src/keys/secp256k1-class.js, src/keys/secp256k1.js, test/aes/aes.spec.js, test/browser.js, test/crypto.spec.js, test/hmac/hmac.spec.js, test/keys/ed25519.spec.js, test/keys/ephemeral-keys.spec.js, test/keys/key-stretcher.spec.js, test/keys/rsa-crypto-libs.js, test/keys/rsa.spec.js, test/keys/secp256k1.spec.js, test/random-bytes.spec.js, test/util.spec.js, test/util/index.js
Removes multibase/multicodec/multihashing in favour of the implementations in the new multiformats module.
Turns out all we really use is sha2-256 and identity, we don't need all the other stuff it pulls in.
=> chore: upgrades to new multiformats module

package.json
This bumps the version of node-forge to remove a security issue. There's still quite a bit of downloads for the 0.16.x version. The minor version of node-forge only included a breaking change in the supported node version (dropped Node 4), which 0.16.x already does not support, so only a patch is required here.
=> fix: back port node forge bump to 0.16.x

benchmarks/ed25519/index.js, benchmarks/ed25519/package.json
`@noble/ed25519` precomputes a wNAF table of scalar multiplication
on the first invocation of `getPublicKey` so do that ahead of time
to stop it affecting the relative margin of error.
=> chore: precompute table before benchmark

.github/workflows/main.yml, package.json, src/keys/rsa.js
We use `ursa-optional` to geenrate RSA keypairs in node.js, falling back to `keypair` if compilation of `ursa-optional` failed at install time.
Node.js has supported generating RSA keypairs since 10.x so use that instead and remove the `ursa-optional` and `kepair` dependencies.
As a bonus node 15+ also supports `jwk` format keys everywhere so the `pem-jwk` dep can go too.
BREAKING CHANGE: requires node 15+
=> feat: replace keypair and ursa-optional with node crypto

src/keys/ed25519-class.ts, src/keys/rsa-class.ts, src/keys/secp256k1-class.ts
Accept `any` otherwise we aren't compatible with the types in libp2p-intefaces.
=> fix: relax .equals type

package.json
This library does not work with node 15 (#221).
Moreover, node 15 has reached End-of-Life.
Resolves #221.
=> chore: change min node support to 16

package.json
`@noble/ed25519@1.5.0` introduces a regression around signatures so
pin to `1.4.0` while it is resolved.
Refs: https://github.com/paulmillr/noble-ed25519/issues/45
=> fix: pin @noble/ed25519 version

package.json
This makes sure it's always 1.6.0+ and not just 1.4.0 if some dep is also using 1.4.0
https://github.com/paulmillr/noble-ed25519/releases/tag/1.6.0
=> fix: bump noble-ed25519 to an audited version

package.json, src/keys/index.ts, src/keys/keys.ts
Updates protons and regenerates protobuf code to encode/decode enums correctly.
=> fix: encode protobuf enums correctly

src/keys/jwk2pem.ts
Fix: Added .js extension to import in src/keys/jwk2pem.ts
#256 
Before:
import { base64urlToBigInteger } from '../util'
After:
import { base64urlToBigInteger } from '../util.js'
=> fix: Added .js extension to import in src/keys/jwk2pem.ts

benchmark/ed25519/compat.cjs, benchmark/ed25519/index.cjs, benchmark/ed25519/package.json, package.json, src/random-bytes.ts
This dependency brings in NodeJS's `Buffer` which then needs to be polyfilled in the browser.
`@noble/*` already brings a utility that switch between Node's and the browser's `randomBytes` interfaces.
One caveat is that `iso-random-stream` enables generation of arrays greater than 65536 in length in the browser.
It does not strike to me as a feature needed for libp2p-crypto. Let me know your thoughts.
=> fix: remove iso-random-stream dependency

package.json, src/aes/cipher-mode.ts, src/keys/ecdh-browser.ts, src/keys/ecdh.ts, src/keys/ed25519-class.ts, src/keys/index.ts, src/keys/key-stretcher.ts, src/keys/rsa-browser.ts, src/keys/rsa-class.ts, src/keys/rsa-utils.ts, src/keys/rsa.ts, src/keys/secp256k1-class.ts, src/keys/secp256k1.ts, src/pbkdf2.ts, src/random-bytes.ts
Replaces [err-code](https://github.com/IndigoUnited/js-err-code/blob/master/index.js) with [CodeError](https://github.com/libp2p/js-libp2p-interfaces/pull/314)
Related: [js-libp2p#1269](https://github.com/libp2p/js-libp2p/issues/1269)
Changes
- removes err-code from dependencies
- adds @libp2p/interfaces@3.2.0 to dependencies
- uses CodeError in place of err-code
=> chore: replace err-code with CodeError

src/keys/ed25519.ts, test/keys/ed25519.spec.ts
Create a private key object from the raw `Ed25519` private key and export it as a JWK to obtain the public key.
Fixes #295
=> fix: derive ed25519 public key from private key using node crypto

src/ciphers/aes-gcm.browser.ts, test/workaround.spec.ts
=> fix: Remove unreliable webkit-linux useragent check
